// Real German higher-education institutions — sourced from Wikidata (CC0, public
// domain) via SPARQL: instances of the university subclass-tree located in Germany,
// currently operating (has an official website, not dissolved). REAL Layer-1a basis
// for AlmiGoethe study-in-Germany SEO — no fabrication. Granular per-programme data
// (the ~21k Hochschulkompass programmes) is a later, licence-gated wave.

export type GermanUni = { slug: string; name: string; city: string | null; website: string | null };

export const GERMAN_UNIS: GermanUni[] = [
  { slug: "akad-bildungsgesellschaft", name: "AKAD Bildungsgesellschaft", city: "Stuttgart", website: "http://www.akad.de/" },
  { slug: "dpfa-hochschule-sachsen", name: "DPFA Hochschule Sachsen", city: "Leipzig", website: "http://www.dpfa-hs.de/" },
  { slug: "duale-hochschule-baden-wurttemberg-heilbronn", name: "Duale Hochschule Baden-Württemberg Heilbronn", city: "Heilbronn", website: "http://www.heilbronn.dhbw.de/" },
  { slug: "europaische-hochschule-fur-innovation-und-perspektive", name: "Europäische Hochschule für Innovation und Perspektive", city: "Backnang", website: "https://www.ehip.eu/" },
  { slug: "fachhochschule-dresden", name: "Fachhochschule Dresden", city: "Dresden", website: "http://www.fh-dresden.eu/" },
  { slug: "fachhochschule-fur-sport-und-management-potsdam", name: "Fachhochschule für Sport und Management Potsdam", city: "Potsdam", website: "https://www.fhsmp.de/" },
  { slug: "freie-hochschule-stuttgart", name: "Freie Hochschule Stuttgart", city: "Stuttgart", website: "http://www.freie-hochschule-stuttgart.de/" },
  { slug: "freie-hochschule-fur-grafik-design-bildende-kunst-freiburg", name: "Freie Hochschule für Grafik-Design & Bildende Kunst Freiburg", city: "Freiburg im Breisgau", website: "http://www.freie-hochschule-freiburg.de" },
  { slug: "ga-hochschule", name: "GA Hochschule", city: "Berlin", website: "http://www.ga-hochschule.de/" },
  { slug: "german-open-business-school", name: "German open Business School", city: "Berlin", website: "http://www.go-bs.de/" },
  { slug: "hochschule-fur-kommunikation-und-gestaltung", name: "Hochschule für Kommunikation und Gestaltung", city: "Stuttgart", website: "http://www.hfk-bw.de/" },
  { slug: "hochschule-fur-verwaltung-in-niedersachsen", name: "Hochschule für Verwaltung in Niedersachsen", city: null, website: "https://www.nsi-hsvn.de/" },
  { slug: "internationale-hochschule-liebenzell", name: "Internationale Hochschule Liebenzell", city: "Bad Liebenzell", website: "http://www.ihl.eu/" },
  { slug: "internationales-priesterseminar-herz-jesu", name: "Internationales Priesterseminar Herz Jesu", city: "Zaitzkofen", website: "https://zaitzkofen.fsspx.org/" },
  { slug: "kmm-hamburg-institut-fur-kultur-und-medienmanagement", name: "KMM Hamburg – Institut für Kultur- und Medienmanagement", city: "Hamburg", website: "http://www.kmm-hamburg.de/" },
  { slug: "katholische-hochschule-fur-kirchenmusik-rottenburg", name: "Katholische Hochschule für Kirchenmusik Rottenburg", city: "Rottenburg am Neckar", website: "http://www.kirchenmusik-hochschule.org/" },
  { slug: "logistikschule-der-bundeswehr", name: "Logistikschule der Bundeswehr", city: "Osterholz-Scharmbeck", website: "https://www.bundeswehr.de/de/organisation/unterstuetzungsbereich/logistik/logistikkommando-der-bundeswehr-in-erfurt/logistikschule-der-bundeswehr-in-garlstedt/" },
  { slug: "mathias-hochschule-rheine", name: "Mathias Hochschule Rheine", city: "Rheine", website: "http://www.mhrheine.de/" },
  { slug: "media-akademie-hochschule-stuttgart", name: "Media Akademie – Hochschule Stuttgart", city: "Stuttgart", website: "http://www.media-hs.de/" },
  { slug: "ostkreuzschule", name: "Ostkreuzschule", city: "Berlin", website: "https://www.ostkreuzschule.de/" },
  { slug: "priesterseminar-wurzburg", name: "Priesterseminar Würzburg", city: "Würzburg", website: "https://priesterseminar-wuerzburg.de/" },
  { slug: "srh-hochschule-der-popularen-kunste", name: "SRH Hochschule der populären Künste", city: "Berlin", website: "https://www.hdpk.de/" },
  { slug: "srh-university-of-applied-sciences-heidelberg", name: "SRH University of Applied Sciences Heidelberg", city: "Heidelberg", website: "https://www.srh-university.de" },
  { slug: "staatliche-studienakademie-plauen", name: "Staatliche Studienakademie Plauen", city: "Plauen", website: "https://www.ba-plauen.de/" },
  { slug: "steuerakademie-niedersachsen", name: "Steuerakademie Niedersachsen", city: "Bad Eilsen", website: "http://www.steuerakademie.niedersachsen.de/" },
  { slug: "wilhelm-lohe-hochschule-fur-angewandte-wissenschaften", name: "Wilhelm Löhe Hochschule für angewandte Wissenschaften", city: "Fürth", website: "http://www.wlh-fuerth.de/" },
  { slug: "akad-university", name: "AKAD University", city: "Stuttgart", website: "https://www.akad.de/" },
  { slug: "aalen-university-of-applied-sciences", name: "Aalen University of Applied Sciences", city: "Aalen", website: "http://www.hs-aalen.de/" },
  { slug: "academy-for-public-administration-bremen", name: "Academy for public administration Bremen", city: "Bremen", website: "http://www.hfoev.bremen.de/" },
  { slug: "academy-of-fine-arts-leipzig", name: "Academy of Fine Arts Leipzig", city: "Leipzig", website: "http://www.hgb-leipzig.de/" },
  { slug: "academy-of-fine-arts-munster", name: "Academy of Fine Arts Münster", city: "Münster", website: "http://www.kunstakademie-muenster.de/" },
  { slug: "academy-of-fine-arts-karlsruhe", name: "Academy of Fine Arts, Karlsruhe", city: "Karlsruhe", website: "http://www.kunstakademie-karlsruhe.de" },
  { slug: "academy-of-fine-arts-nuremberg", name: "Academy of Fine Arts, Nuremberg", city: "Nuremberg", website: "https://adbk-nuernberg.de" },
  { slug: "academy-of-media-arts-cologne", name: "Academy of Media Arts Cologne", city: "Altstadt-Süd", website: "http://www.khm.de" },
  { slug: "academy-of-performing-arts-baden-wuerttemberg", name: "Academy of Performing Arts Baden-Wuerttemberg", city: "Ludwigsburg", website: "https://adk-bw.de/" },
  { slug: "academy-of-sciences-and-literature-mainz", name: "Academy of Sciences and Literature Mainz", city: "Mainz", website: "http://www.adwmainz.de" },
  { slug: "accadis-business-school-bad-homburg", name: "Accadis Business School Bad Homburg", city: "Bad Homburg vor der Höhe", website: "http://www.accadis.com/" },
  { slug: "akademie-der-polizei-hamburg", name: "Akademie der Polizei Hamburg", city: "Hamburg", website: "http://akademie-der-polizei.hamburg.de" },
  { slug: "akademie-fur-bildende-kunste-mainz-germany", name: "Akademie für Bildende Künste (Mainz, Germany)", city: "Rhineland-Palatinate", website: "http://www.kunsthochschule-mainz.de" },
  { slug: "akkon-university-for-human-sciences", name: "Akkon University for Human Sciences", city: "Berlin", website: "http://www.akkon-hochschule.de/" },
  { slug: "albstadt-sigmaringen-university", name: "Albstadt-Sigmaringen University", city: "Albstadt", website: "https://www.hs-albsig.de/" },
  { slug: "alice-salomon-university", name: "Alice Salomon University", city: "Berlin", website: "https://www.ash-berlin.eu/" },
  { slug: "allensbach-hochschule", name: "Allensbach Hochschule", city: "Constance", website: "http://www.allensbach-hochschule.de" },
  { slug: "ansbach-university-of-applied-sciences", name: "Ansbach University of Applied Sciences", city: "Ansbach", website: "http://www.hs-ansbach.de" },
  { slug: "archivschule-marburg", name: "Archivschule Marburg", city: "Marburg", website: "https://www.archivschule.de/" },
  { slug: "army-officer-academy-germany", name: "Army Officer Academy (Germany)", city: "Dresden", website: "https://www.bundeswehr.de/de/organisation/heer/organisation/ausbildungskommando/offizierschule-des-heeres/" },
  { slug: "aschaffenburg-university-of-applied-sciences", name: "Aschaffenburg University of Applied Sciences", city: "Aschaffenburg", website: "http://www.th-ab.de" },
  { slug: "augsburg-technical-university-of-applied-sciences", name: "Augsburg Technical University of Applied Sciences", city: "Augsburg", website: "http://www.tha.de/" },
  { slug: "augustana-divinity-school", name: "Augustana Divinity School", city: "Neuendettelsau", website: "http://www.augustana.de" },
  { slug: "bbw-university-of-applied-sciences", name: "BBW University of Applied Sciences", city: "Berlin", website: "https://www.bbw-hochschule.de/" },
  { slug: "best-sabel-hochschule-berlin", name: "BEST-Sabel-Hochschule Berlin", city: "Berlin", website: "http://www.bsb-hochschule.de" },
  { slug: "bsp-business-law-school", name: "BSP Business & Law School", city: "Berlin", website: "https://www.businessschool-berlin.de/" },
  { slug: "baden-wuerttemberg-cooperative-state-university-loerrach", name: "Baden-Wuerttemberg Cooperative State University Loerrach", city: "Lörrach", website: "http://www.dhbw-loerrach.de/" },
  { slug: "baden-wurttemberg-cooperative-state-university", name: "Baden-Württemberg Cooperative State University", city: "Baden-Württemberg", website: "http://www.dhbw.de/english.html" },
  { slug: "bard-college-berlin", name: "Bard College Berlin", city: "Berlin", website: "http://www.berlin.bard.edu" },
  { slug: "barenboim-said-akademie", name: "Barenboim–Said Akademie", city: "Berlin", website: "https://barenboimsaid.de" },
  { slug: "bauhaus-universitat-weimar", name: "Bauhaus-Universität Weimar", city: "Thuringia", website: "http://www.uni-weimar.de/" },
  { slug: "bavarian-university-of-applied-sciences-and-management", name: "Bavarian University of Applied Sciences and Management", city: "Munich", website: "http://hdbw-hochschule.de" },
  { slug: "berlin-school-of-business-and-innovation", name: "Berlin School of Business and Innovation", city: "Berlin", website: "https://www.berlinsbi.com/" },
  { slug: "berlin-school-of-economics-and-law", name: "Berlin School of Economics and Law", city: "Berlin", website: "https://www.hwr-berlin.de/" },
  { slug: "berlin-university-of-the-arts", name: "Berlin University of the Arts", city: "Berlin", website: "https://www.udk-berlin.de/" },
  { slug: "berufsakademie-glauchau", name: "Berufsakademie Glauchau", city: "Glauchau", website: "http://www.ba-glauchau.de" },
  { slug: "berufsakademie-wilhelmshaven", name: "Berufsakademie Wilhelmshaven", city: "Wilhelmshaven", website: "https://www.berufsakademie-wilhelmshaven.de" },
  { slug: "bielefeld-university", name: "Bielefeld University", city: "North Rhine-Westphalia", website: "https://www.uni-bielefeld.de/" },
  { slug: "bildungszentrum-der-thuringer-landesverwaltung-gotha", name: "Bildungszentrum der Thüringer Landesverwaltung Gotha", city: "Gotha", website: "https://bildungszentrum.thueringen.de/" },
  { slug: "bochum-university-of-applied-sciences", name: "Bochum University of Applied Sciences", city: "Bochum", website: "http://www.hochschule-bochum.de/" },
  { slug: "bonn-rhein-sieg-university-of-applied-sciences", name: "Bonn-Rhein-Sieg University of Applied Sciences", city: "Sankt Augustin", website: "http://www.h-brs.de" },
  { slug: "brand-academy", name: "Brand Academy", city: "Hamburg", website: "http://www.brand-acad.de/" },
  { slug: "brandenburg-university-of-technology-cottbus-senftenberg", name: "Brandenburg University of Technology Cottbus-Senftenberg", city: "Cottbus", website: "http://www.b-tu.de/" },
  { slug: "braunschweig-university-of-art", name: "Braunschweig University of Art", city: "Brunswick", website: "http://www.hbk-bs.de/" },
  { slug: "bremen-university-of-applied-sciences", name: "Bremen University of Applied Sciences", city: "Bremen", website: "http://www.hs-bremen.de/" },
  { slug: "bundesanstalt-fur-materialforschung-und-prufung-bam", name: "Bundesanstalt für Materialforschung und -prüfung (BAM)", city: null, website: "https://www.bam.de/Navigation/DE/Home/home.html" },
  { slug: "burg-giebichenstein-university-of-art-and-design-halle", name: "Burg Giebichenstein University of Art and Design Halle", city: "Halle (Saale)", website: "https://www.burg-halle.de/" },
  { slug: "cbs-international-business-school", name: "CBS International Business School", city: "Cologne", website: "http://www.cbs-edu.de/" },
  { slug: "code-university-of-applied-sciences", name: "CODE University of Applied Sciences", city: "Berlin", website: "https://code.berlin" },
  { slug: "campus-kunzelsau-reinhold-wurth-hochschule", name: "Campus Künzelsau - Reinhold-Würth-Hochschule", city: "Künzelsau", website: "http://www.hs-heilbronn.de/twk" },
  { slug: "catholic-faculty-of-theology-in-munich", name: "Catholic Faculty of Theology in Munich", city: null, website: "http://www.kaththeol.uni-muenchen.de/" },
  { slug: "catholic-theological-faculty-of-the-university-of-erfurt", name: "Catholic Theological Faculty of the University of Erfurt", city: null, website: "https://www.uni-erfurt.de/katholisch-theologische-fakultaet" },
  { slug: "catholic-university-of-applied-sciences-freiburg", name: "Catholic University of Applied Sciences Freiburg", city: "Freiburg im Breisgau", website: "http://www.kh-freiburg.de/" },
  { slug: "catholic-university-of-applied-sciences-mainz", name: "Catholic University of Applied Sciences Mainz", city: "Mainz", website: "https://www.kh-mz.de/katholische-hochschule/" },
  { slug: "catholic-university-of-applied-social-sciences", name: "Catholic University of Applied Social Sciences", city: "Berlin", website: "https://www.khsb-berlin.de/" },
  { slug: "catholic-university-of-eichstatt-ingolstadt", name: "Catholic University of Eichstätt-Ingolstadt", city: "Bavaria", website: "https://www.ku.de/en/" },
  { slug: "center-for-jewish-studies-heidelberg", name: "Center for Jewish Studies Heidelberg", city: "Heidelberg", website: "http://www.hfjs.eu/" },
  { slug: "charlotte-fresenius-university", name: "Charlotte Fresenius University", city: "Cologne", website: "https://www.charlotte-fresenius-uni.de/" },
  { slug: "chemnitz-university-of-technology", name: "Chemnitz University of Technology", city: "Chemnitz", website: "https://www.tu-chemnitz.de/" },
  { slug: "clausthal-university-of-technology", name: "Clausthal University of Technology", city: "Clausthal-Zellerfeld", website: "http://www.tu-clausthal.de/" },
  { slug: "coburg-university-of-applied-sciences", name: "Coburg University of Applied Sciences", city: "Coburg", website: "http://www.hs-coburg.de/" },
  { slug: "college-of-church-music-dresden", name: "College of Church Music Dresden", city: "Dresden", website: "http://www.kirchenmusik-dresden.de/" },
  { slug: "college-of-economics-for-management", name: "College of Economics for Management", city: "Mannheim", website: "http://www.hdwm.de/" },
  { slug: "collegium-borromaeum", name: "Collegium Borromaeum", city: "Freiburg im Breisgau", website: "http://www.cb-freiburg.de/" },
  { slug: "collegium-willibaldicum", name: "Collegium Willibaldicum", city: "Eichstätt", website: "https://www.priesterseminar-eichstaett.de/startseite/" },
  { slug: "cologne-university-of-catholic-theology", name: "Cologne University of Catholic Theology", city: "Cologne", website: "https://www.khkt.de/" },
  { slug: "columbia-international-university-korntal", name: "Columbia International University Korntal", city: null, website: "https://www.ciu.edu/ciu-korntal" },
  { slug: "constance-university-of-applied-sciences", name: "Constance University of Applied Sciences", city: "Constance", website: "http://www.htwg-konstanz.de/English.20.0.html" },
  { slug: "constructor-university", name: "Constructor University", city: "Bremen", website: "https://constructor.university/" },
  { slug: "dhbw-karlsruhe", name: "DHBW Karlsruhe", city: "Karlsruhe", website: "https://www.karlsruhe.dhbw.de/" },
  { slug: "dhbw-mosbach", name: "DHBW Mosbach", city: "Mosbach", website: "http://www.dhbw-mosbach.de/" },
  { slug: "dhbw-stuttgart", name: "DHBW Stuttgart", city: "Stuttgart", website: "http://dhbw-stuttgart.de/" },
  { slug: "darmstadt-university-of-applied-sciences", name: "Darmstadt University of Applied Sciences", city: "Darmstadt", website: "http://www.h-da.de/" },
  { slug: "deggendorf-institute-of-technology", name: "Deggendorf Institute of Technology", city: "Deggendorf", website: "https://www.th-deg.de/" },
  { slug: "design-akademie-berlin-srh-hochschule-fur-kommunikation-und-design", name: "Design akademie berlin, SRH Hochschule für Kommunikation und Design", city: "Berlin", website: "http://www.design-akademie-berlin.de" },
  { slug: "deutsche-hochschule-fur-gesundheit-und-sport", name: "Deutsche Hochschule für Gesundheit und Sport", city: null, website: "https://www.dhgs-hochschule.de" },
  { slug: "deutsche-hochschule-fur-pravention-und-gesundheitsmanagement", name: "Deutsche Hochschule für Prävention und Gesundheitsmanagement", city: "Saarbrücken", website: "https://www.dhfpg.de/" },
  { slug: "diploma-hochschule", name: "Diploma Hochschule", city: "Bad Sooden-Allendorf", website: "http://diploma.de/" },
  { slug: "divine-faculty-of-fulda", name: "Divine Faculty of Fulda", city: "Fulda", website: "http://en.thf-fulda.de/" },
  { slug: "dortmund-university-of-applied-sciences-and-arts", name: "Dortmund University of Applied Sciences and Arts", city: "Dortmund", website: "http://www.fh-dortmund.de/" },
  { slug: "dresden-academy-of-fine-arts", name: "Dresden Academy of Fine Arts", city: "Dresden", website: "http://www.hfbk-dresden.de" },
  { slug: "dresden-international-university", name: "Dresden International University", city: "Dresden", website: "http://www.di-uni.de/" },
  { slug: "duale-hochschule-baden-wurttemberg-heidenheim", name: "Duale Hochschule Baden-Württemberg Heidenheim", city: "Heidenheim an der Brenz", website: "http://www.dhbw-heidenheim.de/" },
  { slug: "duale-hochschule-baden-wurttemberg-mannheim", name: "Duale Hochschule Baden-Württemberg Mannheim", city: "Mannheim", website: "http://www.dhbw-mannheim.de/" },
  { slug: "duale-hochschule-baden-wurttemberg-villingen-schwenningen", name: "Duale Hochschule Baden-Württemberg Villingen-Schwenningen", city: "Baden-Württemberg", website: "https://www.dhbw-vs.de/" },
  { slug: "duale-hochschule-gera-eisenach", name: "Duale Hochschule Gera-Eisenach", city: "Gera", website: "http://www.dhge.de" },
  { slug: "duale-hochschule-schleswig-holstein", name: "Duale Hochschule Schleswig-Holstein", city: "Schleswig-Holstein", website: "https://www.dhsh.de/" },
  { slug: "ducal-georgianum", name: "Ducal Georgianum", city: "Munich", website: "http://www.herzoglichesgeorgianum.de/" },
  { slug: "ebc-hochschule", name: "EBC Hochschule", city: "Hamburg", website: "http://www.ebc-hochschule.de/" },
  { slug: "ebs-universitat-fur-wirtschaft-und-recht", name: "EBS Universität für Wirtschaft und Recht", city: "Wiesbaden", website: "http://www.ebs.edu/" },
  { slug: "ebz-business-school", name: "EBZ Business School", city: "Bochum", website: "http://www.ebz-business-school.de/" },
  { slug: "escp-business-school", name: "ESCP Business School", city: "Berlin", website: "https://escp.eu/" },
  { slug: "eu-business-school", name: "EU Business School", city: "Geneva", website: "https://www.euruni.edu" },
  { slug: "eberswalde-university-for-sustainable-development", name: "Eberswalde University for Sustainable Development", city: "Eberswalde", website: "http://www.hnee.de" },
  { slug: "environment-campus-birkenfeld", name: "Environment Campus Birkenfeld", city: "Hoppstädten-Weiersbach", website: "http://www.umwelt-campus.de/ucb/index.php?id=home&L=1" },
  { slug: "ernst-busch-academy-of-dramatic-arts", name: "Ernst Busch Academy of Dramatic Arts", city: "Berlin", website: "https://www.hfs-berlin.de/" },
  { slug: "esslingen-university-of-applied-sciences", name: "Esslingen University of Applied Sciences", city: "Esslingen am Neckar", website: "http://www.hs-esslingen.de" },
  { slug: "european-fernhochschule-hamburg", name: "European Fernhochschule Hamburg", city: "Hamburg", website: "https://www.euro-fh.de/" },
  { slug: "european-open-university", name: "European Open University", city: "Hambühren", website: "https://academyeurope.eu/" },
  { slug: "european-school-of-management-and-technology", name: "European School of Management and Technology", city: "Berlin", website: "https://esmt.berlin/" },
  { slug: "european-university-viadrina", name: "European University Viadrina", city: "Frankfurt (Oder)", website: "https://www.europa-uni.de" },
  { slug: "european-university-of-applied-sciences", name: "European University of Applied Sciences", city: "Brühl", website: "http://www.eufh.de/" },
  { slug: "evangelical-school-of-social-work-diakonie", name: "Evangelical School of Social Work & Diakonie", city: "Hamburg", website: "http://www.ev-hochschule-hh.de/" },
  { slug: "evangelische-hochschule-darmstadt", name: "Evangelische Hochschule Darmstadt", city: "Darmstadt", website: "http://www.eh-darmstadt.de/" },
  { slug: "evangelische-hochschule-fur-kirchenmusik-tubingen", name: "Evangelische Hochschule für Kirchenmusik Tübingen", city: "Tübingen", website: "https://www.kirchenmusikhochschule.de/" },
  { slug: "fh-aachen", name: "FH Aachen", city: "Aachen", website: "https://www.fh-aachen.de/" },
  { slug: "fh-diakonie-bielefeld", name: "FH Diakonie, Bielefeld", city: "Bielefeld", website: "https://www.fh-diakonie.de/" },
  { slug: "fh-munster", name: "FH Münster", city: "Münster", website: "https://www.fh-muenster.de/" },
  { slug: "fom-university-of-applied-sciences", name: "FOM University of Applied Sciences", city: "Essen", website: "https://www.fom-international.com/" },
  { slug: "fachhochschule-clara-hoffbauer-potsdam", name: "Fachhochschule Clara Hoffbauer Potsdam", city: "Potsdam", website: "https://www.fhchp.de/" },
  { slug: "fachhochschule-ottersberg", name: "Fachhochschule Ottersberg", city: "Ottersberg", website: "http://www.hks-ottersberg.de//" },
  { slug: "fachhochschule-westkuste", name: "Fachhochschule Westküste", city: "Schleswig-Holstein", website: "http://www.fh-westkueste.de/" },
  { slug: "fachhochschule-der-wirtschaft", name: "Fachhochschule der Wirtschaft", city: "Paderborn", website: "https://www.fhdw.de/" },
  { slug: "fachhochschule-des-bundes-fur-offentliche-verwaltung", name: "Fachhochschule des Bundes für öffentliche Verwaltung", city: "Brühl", website: "http://www.hsbund.de/" },
  { slug: "fachhochschule-des-mittelstands", name: "Fachhochschule des Mittelstands", city: "North Rhine-Westphalia", website: "http://www.fh-mittelstand.de/" },
  { slug: "fachhochschule-fur-finanzen-brandenburg", name: "Fachhochschule für Finanzen Brandenburg", city: "Königs Wusterhausen", website: "https://fhf.brandenburg.de/" },
  { slug: "fachhochschule-fur-rechtspflege-nrw", name: "Fachhochschule für Rechtspflege NRW", city: "Bad Münstereifel", website: "http://www.fhr.nrw.de/" },
  { slug: "fachhochschule-fur-die-wirtschaft", name: "Fachhochschule für die Wirtschaft", city: "Hanover", website: "http://www.fhdw-hannover.de/" },
  { slug: "federal-academy-for-security-policy", name: "Federal Academy for Security Policy", city: "Berlin", website: "https://www.baks.bund.de/" },
  { slug: "fernuniversitat-in-hagen", name: "FernUniversität in Hagen", city: "Hagen", website: "https://www.fernuni-hagen.de/" },
  { slug: "film-academy-baden-wurttemberg", name: "Film Academy Baden-Württemberg", city: "Ludwigsburg", website: "http://www.filmakademie.de/" },
  { slug: "flensburg-university-of-applied-sciences", name: "Flensburg University of Applied Sciences", city: "Flensburg", website: "https://hs-flensburg.de/" },
  { slug: "folkwang-university-of-the-arts", name: "Folkwang University of the Arts", city: "Dortmund", website: "http://www.folkwang-uni.de/" },
  { slug: "franco-german-legal-centre", name: "Franco-German Legal Centre", city: "Saarbrücken", website: "https://www.cjfa.eu/" },
  { slug: "frankfurt-university-of-applied-sciences", name: "Frankfurt University of Applied Sciences", city: "Frankfurt", website: "https://www.frankfurt-university.de/" },
  { slug: "frankfurt-university-of-music-and-performing-arts", name: "Frankfurt University of Music and Performing Arts", city: "Frankfurt", website: "http://www.hfmdk-frankfurt.info/" },
  { slug: "freiberg-university-of-mining-and-technology", name: "Freiberg University of Mining and Technology", city: "Freiberg", website: "https://tu-freiberg.de/" },
  { slug: "freie-universitat-berlin", name: "Freie Universität Berlin", city: "Berlin", website: "https://www.fu-berlin.de/" },
  { slug: "friedensau-adventist-university", name: "Friedensau Adventist University", city: "Möckern", website: "https://www.thh-friedensau.de/" },
  { slug: "friedrich-schiller-university-jena", name: "Friedrich Schiller University Jena", city: "Jena", website: "https://www.uni-jena.de/" },
  { slug: "fulda-university-of-applied-sciences", name: "Fulda University of Applied Sciences", city: "Fulda", website: "http://www.hs-fulda.de/" },
  { slug: "furtwangen-university", name: "Furtwangen University", city: "Furtwangen im Schwarzwald", website: "https://www.hs-furtwangen.de/" },
  { slug: "german-international-university", name: "German International University", city: "Berlin", website: "https://giu-berlin.de/" },
  { slug: "german-police-academy", name: "German Police Academy", city: "Münster", website: "http://www.dhpol.de" },
  { slug: "german-sport-university-cologne", name: "German Sport University Cologne", city: null, website: "https://www.dshs-koeln.de/" },
  { slug: "german-university-of-administrative-sciences-speyer", name: "German University of Administrative Sciences Speyer", city: "Speyer", website: "https://www.uni-speyer.de/" },
  { slug: "german-university-of-applied-labour-studies", name: "German University of Applied Labour Studies", city: "Schwerin", website: "http://www.hdba.de/" },
  { slug: "german-university-of-digital-science", name: "German University of Digital Science", city: "Potsdam", website: "https://german-uds.de/" },
  { slug: "giessen-school-of-theology", name: "Giessen School of Theology", city: "Giessen", website: "http://www.fthgiessen.de/" },
  { slug: "goethe-university-frankfurt", name: "Goethe University Frankfurt", city: "Frankfurt", website: "https://www.goethe-university-frankfurt.de/" },
  { slug: "graduate-school-lubeck", name: "Graduate School Lübeck", city: "Lübeck", website: "http://www.gradschool.uni-luebeck.de" },
  { slug: "graduate-school-rhein-neckar", name: "Graduate School Rhein-Neckar", city: "Ludwigshafen", website: "http://www.gsrn.de" },
  { slug: "hawk-university-of-applied-sciences-and-arts", name: "HAWK University of Applied Sciences and Arts", city: "Hildesheim", website: "https://www.hawk.de/" },
  { slug: "hfh-hamburger-fern-hochschule", name: "HFH · Hamburger Fern-Hochschule", city: "Hamburg", website: "https://www.hfh-fernstudium.de" },
  { slug: "hmu-health-and-medical-university", name: "HMU Health and Medical University", city: "Potsdam", website: "https://www.health-and-medical-university.de/" },
  { slug: "hr-nord", name: "HR Nord", city: "Hildesheim", website: "http://www.fhr-nord.niedersachsen.de/" },
  { slug: "hsd-hochschule-dopfer", name: "HSD Hochschule Döpfer", city: "Cologne", website: "http://www.hs-doepfer.de/" },
  { slug: "htw-berlin", name: "HTW Berlin", city: "Berlin", website: "https://www.htw-berlin.de/" },
  { slug: "hafencity-university-hamburg", name: "HafenCity University Hamburg", city: "Hamburg", website: "https://www.hcu-hamburg.de" },
  { slug: "hamburg-university-of-applied-sciences", name: "Hamburg University of Applied Sciences", city: "Hamburg", website: "https://www.haw-hamburg.de/" },
  { slug: "hamburg-university-of-music-and-drama", name: "Hamburg University of Music and Drama", city: "Hamburg", website: "https://www.hfmt-hamburg.de/" },
  { slug: "hamburg-university-of-technology", name: "Hamburg University of Technology", city: "Harburg", website: "https://www.tuhh.de/" },
  { slug: "hamm-lippstadt-university-of-applied-sciences", name: "Hamm-Lippstadt University of Applied Sciences", city: "Hamm", website: "http://www.hshl.de/" },
  { slug: "handelshochschule-leipzig", name: "Handelshochschule Leipzig", city: "Leipzig", website: "http://www.hhl.de/" },
  { slug: "hannover-medical-school", name: "Hannover Medical School", city: "Buchholz-Kleefeld", website: "https://www.mhh.de/" },
  { slug: "hanns-eisler-music-school-berlin", name: "Hanns Eisler Music School Berlin", city: "Berlin", website: "https://www.hfm-berlin.de/" },
  { slug: "hanover-university-of-music-drama-and-media", name: "Hanover University of Music, Drama and Media", city: "Mitte", website: "https://www.hmtm-hannover.de/" },
  { slug: "harz-university-of-applied-sciences", name: "Harz University of Applied Sciences", city: "Wernigerode", website: "https://www.hs-harz.de/" },
  { slug: "heidelberg-university", name: "Heidelberg University", city: "Heidelberg", website: "https://www.uni-heidelberg.de/" },
  { slug: "heidelberg-university-of-education", name: "Heidelberg University of Education", city: "Heidelberg", website: "http://www.ph-heidelberg.de/" },
  { slug: "heilbronn-business-school", name: "Heilbronn Business School", city: "Heilbronn", website: "http://www.ggs.de/" },
  { slug: "heilbronn-university-of-applied-sciences", name: "Heilbronn University of Applied Sciences", city: "Heilbronn", website: "http://www.hs-heilbronn.de/" },
  { slug: "helmut-schmidt-university", name: "Helmut Schmidt University", city: "Hamburg", website: "https://www.hsu-hh.de/" },
  { slug: "hermannsburg-mission-seminary", name: "Hermannsburg Mission Seminary", city: "Südheide", website: "http://www.fh-hermannsburg.de/" },
  { slug: "hertie-school", name: "Hertie School", city: "Berlin", website: "http://www.hertie-school.org/" },
  { slug: "hesse-state-university-of-applied-sciences-for-police-and-public-administration-management", name: "Hesse State University of Applied Sciences for Police and Public Administration Management", city: null, website: "https://hoems.hessen.de" },
  { slug: "hochschule-anhalt", name: "Hochschule Anhalt", city: "Köthen", website: "https://www.hs-anhalt.de" },
  { slug: "hochschule-bielefeld-university-of-applied-sciences-and-arts", name: "Hochschule Bielefeld - University of Applied Sciences and Arts", city: "Bielefeld", website: "https://www.hsbi.de/" },
  { slug: "hochschule-dusseldorf", name: "Hochschule Düsseldorf", city: "Düsseldorf", website: "https://www.hs-duesseldorf.de/" },
  { slug: "hochschule-emden-leer", name: "Hochschule Emden / Leer", city: "Lower Saxony", website: "http://www.hs-emden-leer.de/" },
  { slug: "hochschule-fresenius-university-of-applied-sciences", name: "Hochschule Fresenius University of Applied Sciences", city: "New York City", website: "http://www.hs-fresenius.de/en/" },
  { slug: "hochschule-geisenheim-university", name: "Hochschule Geisenheim University", city: "Geisenheim", website: "http://www.hs-geisenheim.de/" },
  { slug: "hochschule-hannover", name: "Hochschule Hannover", city: "Hanover", website: "https://hs-hannover.de/" },
  { slug: "hochschule-lausitz", name: "Hochschule Lausitz", city: "Cottbus", website: "http://www.hs-lausitz.de" },
  { slug: "hochschule-mittweida", name: "Hochschule Mittweida", city: "Mittweida", website: "http://www.hs-mittweida.de/" },
  { slug: "hochschule-niederrhein", name: "Hochschule Niederrhein", city: "North Rhine-Westphalia", website: "https://www.hs-niederrhein.de/" },
  { slug: "hochschule-stralsund", name: "Hochschule Stralsund", city: "Stralsund", website: "https://www.hochschule-stralsund.de/" },
  { slug: "hochschule-weserbergland", name: "Hochschule Weserbergland", city: "Hamelin", website: "https://www.hsw-hameln.de/" },
  { slug: "hochschule-wismar-university-of-applied-sciences-technology-business-and-design", name: "Hochschule Wismar, University of Applied Sciences: Technology, Business and Design", city: "Wismar", website: "http://www.hs-wismar.de" },
  { slug: "hochschule-der-deutschen-bundesbank", name: "Hochschule der Deutschen Bundesbank", city: "Hachenburg", website: "https://www.hochschule-bundesbank.de" },
  { slug: "hochschule-der-deutschen-gesetzlichen-unfallversicherung", name: "Hochschule der Deutschen Gesetzlichen Unfallversicherung", city: "Bad Hersfeld", website: "https://www.dguv.de/hochschule/" },
  { slug: "hochschule-der-polizei-des-landes-brandenburg", name: "Hochschule der Polizei des Landes Brandenburg", city: "Oranienburg", website: "https://hpolbb.de/" },
  { slug: "hochschule-der-bildenden-kunste-essen", name: "Hochschule der bildenden Künste Essen", city: "Essen", website: "http://www.hbk-essen.de/" },
  { slug: "hochschule-fur-finanzen-rheinland-pfalz", name: "Hochschule für Finanzen Rheinland-Pfalz", city: "Edenkoben", website: "http://www.fachhochschule-edenkoben.de/" },
  { slug: "hochschule-fur-gesellschaftsgestaltung", name: "Hochschule für Gesellschaftsgestaltung", city: "Koblenz", website: "https://www.hfgg.de" },
  { slug: "hochschule-fur-gestaltung-offenbach", name: "Hochschule für Gestaltung Offenbach", city: "Offenbach am Main", website: "http://www.hfg-offenbach.de/" },
  { slug: "hochschule-fur-gestaltung-schwabisch-gmund", name: "Hochschule für Gestaltung Schwäbisch Gmünd", city: "Schwäbisch Gmünd", website: "http://www.hfg-gmuend.de" },
  { slug: "hochschule-fur-katholische-kirchenmusik-und-musikpadagogik-regensburg", name: "Hochschule für Katholische Kirchenmusik und Musikpädagogik Regensburg", city: "Regensburg", website: "http://www.hfkm-regensburg.de/" },
  { slug: "hochschule-fur-kirchenmusik-heidelberg", name: "Hochschule für Kirchenmusik Heidelberg", city: "Heidelberg", website: "http://www.hfk-heidelberg.de" },
  { slug: "hochschule-fur-kirchenmusik-der-evangelischen-kirche-von-westfalen", name: "Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen", city: "Herford", website: "http://www.hochschule-herford.de/" },
  { slug: "hochschule-fur-musik-carl-maria-von-weber", name: "Hochschule für Musik Carl Maria von Weber", city: "Dresden", website: "http://www.hfmdd.de" },
  { slug: "hochschule-fur-musik-detmold", name: "Hochschule für Musik Detmold", city: "North Rhine-Westphalia", website: "http://www.hfm-detmold.de/" },
  { slug: "hochschule-fur-musik-franz-liszt-weimar", name: "Hochschule für Musik Franz Liszt Weimar", city: "Weimar", website: "http://www.hfm-weimar.de/" },
  { slug: "hochschule-fur-musik-freiburg", name: "Hochschule für Musik Freiburg", city: "Freiburg im Breisgau", website: "http://www.mh-freiburg.de" },
  { slug: "hochschule-fur-musik-karlsruhe", name: "Hochschule für Musik Karlsruhe", city: "Karlsruhe", website: "http://www.hfm-karlsruhe.de" },
  { slug: "hochschule-fur-musik-mainz", name: "Hochschule für Musik Mainz", city: "Mainz", website: "http://www.hfm-mainz.de" },
  { slug: "hochschule-fur-musik-wurzburg", name: "Hochschule für Musik Würzburg", city: "Würzburg", website: "https://www.hfm-wuerzburg.de" },
  { slug: "hochschule-fur-musik-und-tanz-koln", name: "Hochschule für Musik und Tanz Köln", city: "Altstadt-Nord", website: "http://www.hfmt-koeln.de/" },
  { slug: "hochschule-fur-politik-munchen", name: "Hochschule für Politik München", city: null, website: "https://www.hfp.tum.de/hfp/" },
  { slug: "hochschule-fur-polizei-und-offentliche-verwaltung-nordrhein-westfalen", name: "Hochschule für Polizei und öffentliche Verwaltung Nordrhein-Westfalen", city: "North Rhine-Westphalia", website: "https://www.hspv.nrw.de/" },
  { slug: "hochschule-fur-angewandte-padagogik", name: "Hochschule für angewandte Pädagogik", city: "Berlin", website: "http://www.hsap.de/" },
  { slug: "hochschule-fur-bildende-kunste-hamburg", name: "Hochschule für bildende Künste Hamburg", city: "Hamburg-Nord", website: "http://www.hfbk-hamburg.de/" },
  { slug: "hochschule-fur-evangelische-kirchenmusik-bayreuth", name: "Hochschule für evangelische Kirchenmusik Bayreuth", city: "Bayreuth", website: "https://www.hfk-bayreuth.de/" },
  { slug: "hochschule-fur-internationale-wirtschaft-und-logistik", name: "Hochschule für internationale Wirtschaft und Logistik", city: "Bremen", website: "http://www.iubh-dualesstudium.de" },
  { slug: "hochschule-fur-offentliche-verwaltung-rheinland-pfalz", name: "Hochschule für Öffentliche Verwaltung Rheinland Pfalz", city: "Mayen", website: "http://www.hoev-rlp.de/" },
  { slug: "humanistische-hochschule-berlin", name: "Humanistische Hochschule Berlin", city: "Berlin", website: "https://humanistische-hochschule-berlin.de/" },
  { slug: "humboldt-universitat-zu-berlin", name: "Humboldt-Universität zu Berlin", city: "Berlin", website: "https://www.hu-berlin.de/" },
  { slug: "ib-hochschule-berlin", name: "IB-Hochschule Berlin", city: "Berlin", website: "http://www.ib-hochschule.de" },
  { slug: "ist-hochschule-fur-management", name: "IST-Hochschule für Management", city: "Düsseldorf", website: "https://www.ist-hochschule.de/" },
  { slug: "iu-international-university-of-applied-sciences", name: "IU International University of Applied Sciences", city: null, website: "https://www.iu.de/" },
  { slug: "international-psychoanalytic-university-berlin", name: "International Psychoanalytic University Berlin", city: "Berlin", website: "https://www.ipu-berlin.de/" },
  { slug: "international-school-of-management", name: "International School of Management", city: "Dortmund", website: "http://www.ism.de/" },
  { slug: "international-university-of-cooperative-education", name: "International University of Cooperative Education", city: "Darmstadt", website: "http://www.iba-darmstadt.com/" },
  { slug: "jacobs-university-bremen", name: "Jacobs University Bremen", city: "Vegesack", website: "http://www.jacobs-university.de/" },
  { slug: "jade-university-of-applied-sciences", name: "Jade University of Applied Sciences", city: "Lower Saxony", website: "http://www.jade-hs.de" },
  { slug: "johannes-gutenberg-university-mainz", name: "Johannes Gutenberg University Mainz", city: "Mainz", website: "https://www.uni-mainz.de/" },
  { slug: "karlshochschule-international-university", name: "Karlshochschule International University", city: "Karlsruhe", website: "http://www.karlshochschule.de/" },
  { slug: "karlsruhe-institute-of-technology", name: "Karlsruhe Institute of Technology", city: "Karlsruhe", website: "https://www.kit.edu/" },
  { slug: "karlsruhe-university-of-applied-sciences", name: "Karlsruhe University of Applied Sciences", city: "Karlsruhe", website: "https://www.h-ka.de/" },
  { slug: "karlsruhe-university-of-arts-and-design", name: "Karlsruhe University of Arts and Design", city: "Karlsruhe", website: "https://hfg-karlsruhe.de/en/" },
  { slug: "karlsruhe-university-of-education", name: "Karlsruhe University of Education", city: "Karlsruhe", website: "https://www.ph-karlsruhe.de/" },
  { slug: "katholische-hochschule-nordrhein-westfalen", name: "Katholische Hochschule Nordrhein-Westfalen", city: "Aachen", website: "http://www.katho-nrw.de/" },
  { slug: "katholische-stiftungshochschule-munchen", name: "Katholische Stiftungshochschule München", city: "Munich", website: "http://www.ksfh.de/" },
  { slug: "kempten-university-of-applied-sciences", name: "Kempten University of Applied Sciences", city: "Kempten", website: "http://www.hochschule-kempten.de/" },
  { slug: "kiel-university", name: "Kiel University", city: "Schleswig-Holstein", website: "https://www.uni-kiel.de/de/" },
  { slug: "kiel-university-of-applied-science", name: "Kiel University of Applied Science", city: "Kiel", website: "https://www.fh-kiel.de/" },
  { slug: "konrad-wolf-film-university-of-babelsberg", name: "Konrad Wolf Film University of Babelsberg", city: "Potsdam", website: "http://www.filmuniversitaet.de/" },
  { slug: "kuehne-logistics-university", name: "Kuehne Logistics University", city: "Hamburg", website: "http://www.the-klu.org" },
  { slug: "kunstakademie-dusseldorf", name: "Kunstakademie Düsseldorf", city: "Düsseldorf", website: "http://www.kunstakademie-duesseldorf.de/" },
  { slug: "leibniz-university-hannover", name: "Leibniz University Hannover", city: "Hanover", website: "https://www.uni-hannover.de/" },
  { slug: "leibniz-university-of-applied-sciences", name: "Leibniz University of Applied Sciences", city: "Hanover", website: "http://www.leibniz-fh.de/" },
  { slug: "leipzig-university", name: "Leipzig University", city: "Leipzig", website: "https://www.uni-leipzig.de/" },
  { slug: "leipzig-university-of-applied-sciences", name: "Leipzig University of Applied Sciences", city: null, website: "https://www.htwk-leipzig.de/en/htwk-leipzig/" },
  { slug: "leuphana-university-of-luneburg", name: "Leuphana University of Lüneburg", city: "Lüneburg", website: "https://www.leuphana.de/" },
  { slug: "ludwig-maximilians-universitat-munchen", name: "Ludwig-Maximilians-Universität München", city: "Munich", website: "https://www.lmu.de/" },
  { slug: "ludwigsburg-university-of-education", name: "Ludwigsburg University of Education", city: null, website: "https://www.ph-ludwigsburg.de/" },
  { slug: "lutheran-academy-of-theology-oberursel", name: "Lutheran Academy of Theology Oberursel", city: "Oberursel", website: "http://www.lthh-oberursel.de/" },
  { slug: "lutheran-university-of-applied-sciences-nuremberg", name: "Lutheran University of Applied Sciences Nuremberg", city: "Nuremberg", website: "https://www.evhn.de/" },
  { slug: "lubeck-academy-of-music", name: "Lübeck Academy of Music", city: "Lübeck", website: "http://www.mh-luebeck.de/" },
  { slug: "msb-medical-school-berlin", name: "MSB Medical School Berlin", city: "Berlin", website: "http://www.medicalschool-berlin.de/" },
  { slug: "macromedia-university-for-media-and-communication", name: "Macromedia University for Media and Communication", city: "Munich", website: "http://hochschule-macromedia.de/" },
  { slug: "magdeburg-stendal-university-of-applied-sciences", name: "Magdeburg-Stendal University of Applied Sciences", city: "Magdeburg", website: "http://www.hs-magdeburg.de/" },
  { slug: "mainz-university-of-applied-sciences", name: "Mainz University of Applied Sciences", city: "Mainz", website: "http://www.hs-mainz.de/" },
  { slug: "mannheim-technical-university-of-applied-sciences", name: "Mannheim Technical University of Applied Sciences", city: "Mannheim", website: "https://www.hs-mannheim.de/" },
  { slug: "mannheim-university-of-music-and-performing-arts", name: "Mannheim University of Music and Performing Arts", city: "Mannheim", website: "http://www.muho-mannheim.de/" },
  { slug: "marineoperationsschule", name: "Marineoperationsschule", city: "Bremerhaven", website: "https://www.bundeswehr.de/de/organisation/marine/organisation/marineoperationsschule" },
  { slug: "marinetechnikschule", name: "Marinetechnikschule", city: "Kramerhof", website: "https://www.bundeswehr.de/de/organisation/marine/organisation/marinetechnikschule" },
  { slug: "martin-luther-university-halle-wittenberg", name: "Martin Luther University Halle-Wittenberg", city: null, website: "https://www.uni-halle.de/" },
  { slug: "mediadesign-hochschule", name: "Mediadesign Hochschule", city: "Berlin", website: "http://www.mediadesign.de" },
  { slug: "medical-school-hamburg", name: "Medical School Hamburg", city: "Hamburg-Mitte", website: "http://www.medicalschool-hamburg.de/" },
  { slug: "medizinische-hochschule-brandenburg-theodor-fontane", name: "Medizinische Hochschule Brandenburg Theodor Fontane", city: "Neuruppin", website: "http://www.mhb-fontane.de/" },
  { slug: "medizinische-universitat-lausitz-carl-thiem", name: "Medizinische Universität Lausitz – Carl Thiem", city: "Cottbus", website: "https://www.mul-ct.de/" },
  { slug: "merseburg-university-of-applied-sciences", name: "Merseburg University of Applied Sciences", city: null, website: "https://www.hs-merseburg.de/" },
  { slug: "merz-akademie", name: "Merz Akademie", city: "Stuttgart", website: "http://www.merz-akademie.de/" },
  { slug: "mittelhessen-university-of-applied-sciences", name: "Mittelhessen University of Applied Sciences", city: "Giessen", website: "http://www.th-mittelhessen.de/site/" },
  { slug: "moritzburg-protestant-college", name: "Moritzburg Protestant College", city: "Moritzburg", website: "https://tpi-moritzburg.de/" },
  { slug: "munich-business-school", name: "Munich Business School", city: "Laim", website: "https://www.munich-business-school.de/" },
  { slug: "munich-institute-of-media-and-musical-arts", name: "Munich Institute of Media and Musical Arts", city: null, website: "https://mima-university.de/" },
  { slug: "munich-school-of-philosophy", name: "Munich School of Philosophy", city: "Maxvorstadt", website: "http://www.hfph.de/" },
  { slug: "munich-university-of-applied-languages", name: "Munich University of Applied Languages", city: null, website: "http://www.sdi-muenchen.de/hochschule/" },
  { slug: "munich-university-of-applied-sciences", name: "Munich University of Applied Sciences", city: "Munich", website: "http://hm.edu/" },
  { slug: "muthesius-academy-of-art", name: "Muthesius Academy of Art", city: "Schleswig-Holstein", website: "http://www.muthesius-kunsthochschule.de" },
  { slug: "nbs-northern-business-school-hochschule-fur-management-und-sicherheit", name: "NBS Northern Business School - Hochschule für Management und Sicherheit", city: "Wandsbek", website: "http://www.nbs.de/" },
  { slug: "natural-science-and-technical-academy-isny", name: "Natural Science and Technical Academy Isny", city: "Isny im Allgäu", website: "http://www.nta-isny.de" },
  { slug: "naval-academy-at-murwik", name: "Naval Academy at Mürwik", city: "Flensburg", website: "https://www.bundeswehr.de/de/organisation/marine/organisation/marineschule-muerwik" },
  { slug: "naval-damage-control-training-centre", name: "Naval Damage Control Training Centre", city: "Neustadt in Holstein", website: "https://www.bundeswehr.de/de/organisation/marine/organisation/einsatzausbildungszentrum-schadensabwehr" },
  { slug: "naval-medical-institute", name: "Naval Medical Institute", city: "Kiel", website: "https://www.bundeswehr.de/de/organisation/marine/organisation/schifffahrtmedizinisches-institut" },
  { slug: "neubrandenburg-university-of-applied-sciences", name: "Neubrandenburg University of Applied Sciences", city: "Neubrandenburg", website: "https://www.hs-nb.de/" },
  { slug: "nordakademie-hochschule-der-wirtschaft", name: "Nordakademie Hochschule der Wirtschaft", city: "Elmshorn", website: "https://www.nordakademie.de/" },
  { slug: "nurtingen-geislingen-university-of-applied-science", name: "Nürtingen-Geislingen University of Applied Science", city: "Nürtingen", website: "https://www.hfwu.de/" },
  { slug: "oriental-college-of-eichstatt", name: "Oriental College of Eichstätt", city: null, website: "http://www.collegium-orientale.de" },
  { slug: "osnabruck-university", name: "Osnabrück University", city: "Osnabrück", website: "http://www.uni-osnabrueck.de" },
  { slug: "osnabruck-university-of-applied-sciences", name: "Osnabrück University of Applied Sciences", city: "Osnabrück", website: "http://www.hs-osnabrueck.de/" },
  { slug: "ostbayerische-technische-hochschule-amberg-weiden", name: "Ostbayerische Technische Hochschule Amberg-Weiden", city: "Amberg", website: "http://www.oth-aw.de/" },
  { slug: "ostfalia-university-of-applied-sciences", name: "Ostfalia University of Applied Sciences", city: "Lower Saxony", website: "http://www.ostfalia.de" },
  { slug: "otto-stern-school-for-integrated-doctoral-education", name: "Otto Stern School for Integrated Doctoral Education", city: null, website: "http://www.oss.uni-frankfurt.de/" },
  { slug: "palucca-school-of-dance-dresden", name: "Palucca School of Dance, Dresden", city: "Dresden", website: "http://www.palucca.eu/" },
  { slug: "pforzheim-academy", name: "Pforzheim Academy", city: "Pforzheim", website: "http://www.hs-pforzheim.de" },
  { slug: "philosophisch-theologische-hochschule-munster", name: "Philosophisch-Theologische Hochschule Münster", city: "Münster", website: "http://www.pth-muenster.de" },
  { slug: "philosophisch-theologische-hochschule-der-salesianer-don-boscos-benediktbeuern", name: "Philosophisch-Theologische Hochschule der Salesianer Don Boscos Benediktbeuern", city: "Benediktbeuern", website: "http://www.pth-bb.de/" },
  { slug: "popakademie-baden-wurttemberg", name: "Popakademie Baden-Württemberg", city: "Mannheim", website: "http://www.popakademie.de" },
  { slug: "praxis-hochschule-university-of-applied-sciences", name: "Praxis Hochschule University of Applied Sciences", city: "Cologne", website: "http://www.praxishochschule.de" },
  { slug: "priesterseminar-regensburg", name: "Priesterseminar Regensburg", city: "Regensburg", website: "https://www.priesterseminar-regensburg.de/" },
  { slug: "private-hochschule-fur-wirtschaft-und-technik", name: "Private Hochschule für Wirtschaft und Technik", city: "Vechta", website: "http://www.fhwt.de/home.html" },
  { slug: "private-university-of-applied-sciences", name: "Private University of Applied Sciences", city: "Göttingen", website: "https://www.pfh-university.com/" },
  { slug: "protestant-college-for-church-music-in-halle", name: "Protestant College for Church Music in Halle", city: "Halle (Saale)", website: "https://www.ehk-halle.de/" },
  { slug: "protestant-college-for-social-service-dresden", name: "Protestant College for Social service Dresden", city: "Dresden", website: "http://www.ehs-dresden.de/" },
  { slug: "protestant-college-of-tabor", name: "Protestant College of Tabor", city: "Marburg", website: "http://www.eh-tabor.de/" },
  { slug: "protestant-university-ludwigsburg", name: "Protestant University Ludwigsburg", city: "Ludwigsburg", website: "https://www.eh-ludwigsburg.de/en/" },
  { slug: "protestant-university-for-applied-sciences-freiburg", name: "Protestant University for Applied Sciences Freiburg", city: "Freiburg im Breisgau", website: "http://www.eh-freiburg.de" },
  { slug: "protestant-university-of-applied-sciences-berlin", name: "Protestant University of Applied Sciences Berlin", city: "Berlin", website: "https://www.eh-berlin.de" },
  { slug: "provadis-school-of-international-management-and-technology", name: "Provadis School of International Management and Technology", city: "Frankfurt", website: "https://www.provadis-hochschule.de/" },
  { slug: "psychologische-hochschule-berlin", name: "Psychologische Hochschule Berlin", city: "Berlin", website: "http://www.psychologische-hochschule.de/" },
  { slug: "quadriga-hochschule-berlin", name: "Quadriga Hochschule Berlin", city: "Berlin", website: "http://www.quadriga-hochschule.com/" },
  { slug: "rwth-aachen-university", name: "RWTH Aachen University", city: "Aachen", website: "https://www.rwth-aachen.de/" },
  { slug: "ravensburg-university-of-cooperative-education", name: "Ravensburg University of Cooperative Education", city: "Ravensburg", website: "http://www.dhbw-ravensburg.de" },
  { slug: "ravensburg-weingarten-university-of-applied-sciences", name: "Ravensburg-Weingarten University of Applied Sciences", city: "Weingarten", website: "https://www.rwu.de/" },
  { slug: "regensburg-university-of-applied-sciences", name: "Regensburg University of Applied Sciences", city: "Regensburg", website: "http://www.oth-regensburg.de/" },
  { slug: "reutlingen-school-of-theology", name: "Reutlingen School of Theology", city: "Reutlingen", website: "http://www.th-reutlingen.de/" },
  { slug: "reutlingen-university", name: "Reutlingen University", city: null, website: "https://www.reutlingen-university.de/" },
  { slug: "rheinmain-university-of-applied-sciences", name: "RheinMain University of Applied Sciences", city: "Darmstadt Government Region", website: "https://www.hs-rm.de/" },
  { slug: "rheinische-fachhochschule-neuss", name: "Rheinische Fachhochschule Neuss", city: "Neuss", website: "http://www.rfh-neuss.eu/" },
  { slug: "rheinische-hochschule-koln", name: "Rheinische Hochschule Köln", city: "Cologne", website: "https://rh-koeln.de/" },
  { slug: "rheinland-westfalen-lippe-university-of-applied-sciences", name: "Rheinland-Westfalen-Lippe University of Applied Sciences", city: "Bochum", website: "http://www.efh-bochum.de/" },
  { slug: "rhine-waal-university-of-applied-sciences", name: "Rhine-Waal University of Applied Sciences", city: "North Rhine-Westphalia", website: "http://www.hochschule-rhein-waal.de/" },
  { slug: "rhineland-palatinate-police-university-of-applied-sciences", name: "Rhineland-Palatinate Police University of Applied Sciences", city: "Rhineland-Palatinate", website: "https://www.polizei.rlp.de/die-polizei/dienststellen/hochschule-der-polizei-rheinland-pfalz" },
  { slug: "rottenburg-university-of-applied-forest-sciences", name: "Rottenburg University of Applied Forest Sciences", city: "Rottenburg am Neckar", website: "http://www.hs-rottenburg.net" },
  { slug: "ruhr-university-bochum", name: "Ruhr University Bochum", city: "North Rhine-Westphalia", website: "https://www.ruhr-uni-bochum.de/de" },
  { slug: "ruhr-west-university-of-applied-sciences", name: "Ruhr West University of Applied Sciences", city: "Mülheim an der Ruhr", website: "http://en.hochschule-ruhr-west.de/" },
  { slug: "srh-berlin-university-of-applied-sciences", name: "SRH Berlin University of Applied Sciences", city: "Berlin", website: "http://www.srh-hochschule-berlin.de/" },
  { slug: "srh-fernhochschule", name: "SRH Fernhochschule", city: "Riedlingen", website: "https://www.mobile-university.de/de/startseite/" },
  { slug: "srh-hochschule-hamm", name: "SRH Hochschule Hamm", city: "Hamm", website: "http://www.fh-hamm.de" },
  { slug: "srh-hochschule-heidelberg", name: "SRH Hochschule Heidelberg", city: "Heidelberg", website: "http://www.hochschule-heidelberg.de" },
  { slug: "srh-hochschule-for-health-gera", name: "SRH Hochschule for Health Gera", city: "Gera", website: "https://www.srh-university.de/de/unsere-standorte/gera/" },
  { slug: "srh-hochschule-fur-wirtschaft-und-medien-calw", name: "SRH Hochschule für Wirtschaft und Medien Calw", city: "Calw", website: "http://www.hochschule-calw.de" },
  { slug: "srh-university-campus-furth", name: "SRH University Campus Fürth", city: "Fürth", website: "https://www.srh-university.de/de/" },
  { slug: "saar-college-of-fine-arts", name: "Saar College of Fine Arts", city: "Saarbrücken", website: "http://www.hbksaar.de" },
  { slug: "saarland-university", name: "Saarland University", city: "Saarbrücken", website: "https://www.uni-saarland.de/" },
  { slug: "sankt-georgen-graduate-school-of-philosophy-and-theology", name: "Sankt Georgen Graduate School of Philosophy and Theology", city: null, website: "http://www.sankt-georgen.de/" },
  { slug: "saxon-police-force-school", name: "Saxon Police Force School", city: "Rothenburg", website: "http://www.polizei.sachsen.de/de/polfh.htm" },
  { slug: "schmalkalden-university-of-applied-sciences", name: "Schmalkalden University of Applied Sciences", city: null, website: "http://www.hs-schmalkalden.de" },
  { slug: "schwetzingen-technical-institute-graduate-court-registrars-college", name: "Schwetzingen Technical Institute & Graduate Court Registrars' College", city: "Schwetzingen", website: "http://www.fh-schwetzingen.de/" },
  { slug: "sigmund-freud-privatuniversitat-standort-berlin", name: "Sigmund Freud Privatuniversität - Standort Berlin", city: "Berlin", website: "http://www.sfu-berlin.de" },
  { slug: "south-westphalia-university-of-applied-sciences", name: "South Westphalia University of Applied Sciences", city: "Iserlohn", website: "https://www.fh-swf.de/" },
  { slug: "staatliche-studienakademie-breitenbrunn", name: "Staatliche Studienakademie Breitenbrunn", city: "Breitenbrunn/Erzgebirge", website: "http://www.ba-breitenbrunn.de/" },
  { slug: "staatliche-studienakademie-dresden", name: "Staatliche Studienakademie Dresden", city: "Dresden", website: "https://www.dhsn.de/dresden" },
  { slug: "staatliche-studienakademie-leipzig", name: "Staatliche Studienakademie Leipzig", city: "Leipzig", website: "https://www.ba-leipzig.de" },
  { slug: "staatliche-studienakademie-riesa", name: "Staatliche Studienakademie Riesa", city: "Riesa", website: "https://www.ba-riesa.de/" },
  { slug: "state-academy-of-fine-arts-stuttgart", name: "State Academy of Fine Arts Stuttgart", city: null, website: "https://www.abk-stuttgart.de/" },
  { slug: "state-university-of-music-and-performing-arts-stuttgart", name: "State University of Music and Performing Arts Stuttgart", city: "Stuttgart", website: "http://www.mh-stuttgart.de" },
  { slug: "steinbeis-hochschule-berlin", name: "Steinbeis-Hochschule Berlin", city: "Berlin", website: "http://www.steinbeis-hochschule.de/" },
  { slug: "stuttgart-media-university", name: "Stuttgart Media University", city: "Stuttgart", website: "https://www.hdm-stuttgart.de" },
  { slug: "stadelschule", name: "Städelschule", city: "Frankfurt", website: "http://www.staedelschule.de/" },
  { slug: "th-koln-university-of-applied-sciences", name: "TH Köln – University of Applied Sciences", city: "Cologne", website: "https://www.th-koeln.de/" },
  { slug: "thi-technical-university-of-applied-sciences-in-ingolstadt", name: "THI - Technical University of Applied Sciences in Ingolstadt", city: "Ingolstadt", website: "https://www.thi.de/" },
  { slug: "tu-braunschweig", name: "TU Braunschweig", city: "Brunswick", website: "https://www.tu-braunschweig.de/" },
  { slug: "tu-dresden", name: "TU Dresden", city: "Dresden", website: "https://tu-dresden.de/" },
  { slug: "technical-university-of-applied-sciences-wildau", name: "Technical University of Applied Sciences Wildau", city: "Brandenburg", website: "http://www.th-wildau.de/" },
  { slug: "technical-university-of-applied-sciences-wurzburg-schweinfurt", name: "Technical University of Applied Sciences Würzburg-Schweinfurt", city: "Würzburg", website: "http://www.thws.de/" },
  { slug: "technical-university-of-darmstadt", name: "Technical University of Darmstadt", city: "Darmstadt", website: "https://www.tu-darmstadt.de/index.en.jsp" },
  { slug: "technical-university-of-dortmund", name: "Technical University of Dortmund", city: "Dortmund", website: "https://www.tu-dortmund.de/" },
  { slug: "technical-university-of-munich", name: "Technical University of Munich", city: "Munich", website: "https://www.tum.de/" },
  { slug: "technische-hochschule-georg-agricola", name: "Technische Hochschule Georg Agricola", city: "Bochum", website: "https://www.tfh-bochum.de/en/" },
  { slug: "technische-hochschule-lubeck", name: "Technische Hochschule Lübeck", city: "Lübeck", website: "https://www.th-luebeck.de/" },
  { slug: "technische-hochschule-nuremberg-georg-simon-ohm", name: "Technische Hochschule Nuremberg Georg Simon Ohm", city: "Nuremberg", website: "https://www.th-nuernberg.de/" },
  { slug: "technische-hochschule-owl", name: "Technische Hochschule OWL", city: "North Rhine-Westphalia", website: "http://www.th-owl.de/" },
  { slug: "technische-universitat-berlin", name: "Technische Universität Berlin", city: "Berlin", website: "https://www.tu.berlin/" },
  { slug: "technische-universitat-ilmenau", name: "Technische Universität Ilmenau", city: "Ilmenau", website: "https://www.tu-ilmenau.de" },
  { slug: "theological-college-wuppertal-bethel", name: "Theological College Wuppertal/Bethel", city: "Wuppertal", website: "http://www.kiho-wuppertal-bethel.de" },
  { slug: "theological-faculty-of-paderborn", name: "Theological Faculty of Paderborn", city: "Paderborn", website: "http://www.thf-paderborn.de/" },
  { slug: "theologische-fakultat-trier", name: "Theologische Fakultät Trier", city: "Trier", website: "https://theologie-trier.de" },
  { slug: "theologische-hochschule-ewersbach", name: "Theologische Hochschule Ewersbach", city: null, website: "http://th-ewersbach.de/" },
  { slug: "theologisches-seminar-elstal", name: "Theologisches Seminar Elstal", city: "Wustermark", website: "https://www.th-elstal.de/" },
  { slug: "tomorrow-university-of-applied-sciences", name: "Tomorrow University of Applied Sciences", city: "Hesse", website: "https://www.tomorrow.university/" },
  { slug: "touro-college-berlin", name: "Touro College Berlin", city: "Berlin", website: "http://www.touroberlin.com/" },
  { slug: "trier-university", name: "Trier University", city: "Trier", website: "https://www.uni-trier.de/" },
  { slug: "tubingen-university-faculty-of-catholic-theology", name: "Tübingen University Faculty of Catholic Theology", city: "Tübingen", website: "https://www.uni-tuebingen.de/fakultaeten/katholisch-theologische-fakultaet/fakultaet.html" },
  { slug: "ukrainian-free-university", name: "Ukrainian Free University", city: "Neuhausen-Nymphenburg", website: "http://www.ufu-muenchen.de/" },
  { slug: "ulm-school-of-design", name: "Ulm School of Design", city: "Ulm", website: "http://www.hfg-archiv.ulm.de" },
  { slug: "ulm-university", name: "Ulm University", city: "Ulm", website: "https://www.uni-ulm.de/" },
  { slug: "ulm-university-of-applied-sciences", name: "Ulm University of Applied Sciences", city: "Ulm", website: "http://hs-ulm.de" },
  { slug: "united-nations-university-vice-rectorate-in-europe", name: "United Nations University Vice-Rectorate in Europe", city: "Bonn", website: "https://unu.edu/vie" },
  { slug: "university-of-applied-management", name: "University of Applied Management", city: null, website: "https://www.fham.de/" },
  { slug: "university-of-applied-police-sciences-saxony-anhalt", name: "University of Applied Police Sciences Saxony Anhalt", city: null, website: "https://fh-polizei.sachsen-anhalt.de/" },
  { slug: "university-of-applied-sciences-appollon", name: "University of Applied Sciences Appollon", city: "Bremen", website: "http://www.apollon-hochschule.de/" },
  { slug: "university-of-applied-sciences-berlin", name: "University of Applied Sciences Berlin", city: "Bezirk Mitte", website: "https://www.bht-berlin.de/" },
  { slug: "university-of-applied-sciences-biberach", name: "University of Applied Sciences Biberach", city: "Biberach an der Riß", website: "http://www.hochschule-biberach.de/" },
  { slug: "university-of-applied-sciences-bingen", name: "University of Applied Sciences Bingen", city: "Bingen am Rhein", website: "https://www.th-bingen.de" },
  { slug: "university-of-applied-sciences-bremerhaven", name: "University of Applied Sciences Bremerhaven", city: "Bremerhaven", website: "https://www.hs-bremerhaven.de" },
  { slug: "university-of-applied-sciences-dresden", name: "University of Applied Sciences Dresden", city: "Dresden", website: "http://www.htw-dresden.de/" },
  { slug: "university-of-applied-sciences-erfurt", name: "University of Applied Sciences Erfurt", city: "Erfurt", website: "http://www.fh-erfurt.de/" },
  { slug: "university-of-applied-sciences-fliedner-fachhochschule", name: "University of Applied Sciences Fliedner Fachhochschule", city: "Düsseldorf", website: "http://www.fliedner-fachhochschule.de" },
  { slug: "university-of-applied-sciences-hof", name: "University of Applied Sciences Hof", city: "Hof", website: "https://www.hof-university.de/" },
  { slug: "university-of-applied-sciences-jena", name: "University of Applied Sciences Jena", city: "Jena", website: "https://www.eah-jena.de/" },
  { slug: "university-of-applied-sciences-kaiserslautern", name: "University of Applied Sciences Kaiserslautern", city: "Kaiserslautern", website: "https://www.hs-kl.de/" },
  { slug: "university-of-applied-sciences-kehl", name: "University of Applied Sciences Kehl", city: "Kehl", website: "https://www.hs-kehl.de/" },
  { slug: "university-of-applied-sciences-koblenz", name: "University of Applied Sciences Koblenz", city: "Koblenz", website: "http://www.hs-koblenz.de/" },
  { slug: "university-of-applied-sciences-landshut", name: "University of Applied Sciences Landshut", city: "Landshut", website: "http://www.haw-landshut.de/" },
  { slug: "university-of-applied-sciences-ludwigsburg", name: "University of Applied Sciences Ludwigsburg", city: "Ludwigsburg", website: "http://www.hs-ludwigsburg.de/" },
  { slug: "university-of-applied-sciences-ludwigshafen", name: "University of Applied Sciences Ludwigshafen", city: "Ludwigshafen", website: "https://www.hwg-lu.de/" },
  { slug: "university-of-applied-sciences-meissen", name: "University of Applied Sciences Meissen", city: "Meissen", website: "https://www.fhsv.sachsen.de/" },
  { slug: "university-of-applied-sciences-neu-ulm", name: "University of Applied Sciences Neu-Ulm", city: "Neu-Ulm", website: "https://www.hnu.de/" },
  { slug: "university-of-applied-sciences-offenburg", name: "University of Applied Sciences Offenburg", city: "Offenburg", website: "https://www.hs-offenburg.de/" },
  { slug: "university-of-applied-sciences-potsdam", name: "University of Applied Sciences Potsdam", city: "Potsdam", website: "http://www.fh-potsdam.de/" },
  { slug: "university-of-applied-sciences-rosenheim", name: "University of Applied Sciences Rosenheim", city: "Rosenheim", website: "https://www.th-rosenheim.de/" },
  { slug: "university-of-applied-sciences-sparkasse", name: "University of Applied Sciences Sparkasse", city: "Bonn", website: "http://www.s-hochschule.de/" },
  { slug: "university-of-applied-sciences-stuttgart", name: "University of Applied Sciences Stuttgart", city: "Stuttgart", website: "https://www.hft-stuttgart.de/" },
  { slug: "university-of-applied-sciences-trier", name: "University of Applied Sciences Trier", city: "Trier", website: "https://www.hochschule-trier.de/" },
  { slug: "university-of-applied-sciences-wedel", name: "University of Applied Sciences Wedel", city: "Wedel", website: "http://www.fh-wedel.de" },
  { slug: "university-of-applied-sciences-worms", name: "University of Applied Sciences Worms", city: "Worms", website: "https://www.hs-worms.de/" },
  { slug: "university-of-applied-sciences-for-administration-and-services", name: "University of Applied Sciences for Administration and Services", city: "Altenholz", website: "http://www.fhvd.de/" },
  { slug: "university-of-applied-sciences-for-media-communication-and-business", name: "University of Applied Sciences for Media Communication and Business", city: "Berlin", website: "https://www.hmkw.de/" },
  { slug: "university-of-applied-sciences-for-police-baden-wurttemberg", name: "University of Applied Sciences for Police Baden-Württemberg", city: "Baden-Württemberg", website: "https://www.hfpol-bw.de/" },
  { slug: "university-of-applied-sciences-for-public-administration-police-and-justice", name: "University of Applied Sciences for Public Administration, Police and Justice", city: "Güstrow", website: "http://www.fh-guestrow.de/" },
  { slug: "university-of-applied-sciences-in-brandenburg", name: "University of Applied Sciences in Brandenburg", city: "Brandenburg an der Havel", website: "http://www.th-brandenburg.de/" },
  { slug: "university-of-augsburg", name: "University of Augsburg", city: "Augsburg", website: "http://www.uni-augsburg.de/" },
  { slug: "university-of-bamberg", name: "University of Bamberg", city: "Bamberg", website: "https://www.uni-bamberg.de/" },
  { slug: "university-of-bayreuth", name: "University of Bayreuth", city: "Bayreuth", website: "https://www.uni-bayreuth.de/" },
  { slug: "university-of-bonn", name: "University of Bonn", city: "Bonn", website: "https://www.uni-bonn.de" },
  { slug: "university-of-bremen", name: "University of Bremen", city: "Bremen", website: "https://www.uni-bremen.de/" },
  { slug: "university-of-cologne", name: "University of Cologne", city: "Cologne", website: "https://uni-koeln.de" },
  { slug: "university-of-cooperative-education-fulda", name: "University of Cooperative Education Fulda", city: null, website: "https://www.ba-fulda.de/" },
  { slug: "university-of-cooperative-education-melle", name: "University of Cooperative Education Melle", city: "Melle", website: "https://www.ba-melle.de/" },
  { slug: "university-of-cooperative-education-for-banking", name: "University of Cooperative Education for Banking", city: "Hanover", website: "https://www.ba-bankwirtschaft.de/" },
  { slug: "university-of-duisburg-essen", name: "University of Duisburg-Essen", city: "North Rhine-Westphalia", website: "https://www.uni-due.de/" },
  { slug: "university-of-dusseldorf", name: "University of Düsseldorf", city: "North Rhine-Westphalia", website: "https://www.hhu.de/" },
  { slug: "university-of-education-freiburg", name: "University of Education Freiburg", city: "Freiburg im Breisgau", website: "https://www.ph-freiburg.de/" },
  { slug: "university-of-education-schwaebisch-gmuend", name: "University of Education Schwaebisch Gmuend", city: "Schwäbisch Gmünd", website: "http://www.ph-gmuend.de" },
  { slug: "university-of-erfurt", name: "University of Erfurt", city: null, website: "https://www.uni-erfurt.de/" },
  { slug: "university-of-erlangen-nuremberg", name: "University of Erlangen–Nuremberg", city: "Bavaria", website: "https://www.fau.de/" },
  { slug: "university-of-flensburg", name: "University of Flensburg", city: "Schleswig-Holstein", website: "https://www.uni-flensburg.de/" },
  { slug: "university-of-freiburg", name: "University of Freiburg", city: "Freiburg im Breisgau", website: "https://uni-freiburg.de/" },
  { slug: "university-of-giessen", name: "University of Giessen", city: "Giessen", website: "https://www.uni-giessen.de/" },
  { slug: "university-of-greifswald", name: "University of Greifswald", city: "Mecklenburg-Vorpommern", website: "https://www.uni-greifswald.de/" },
  { slug: "university-of-gottingen", name: "University of Göttingen", city: "Göttingen", website: "https://www.uni-goettingen.de/" },
  { slug: "university-of-hamburg", name: "University of Hamburg", city: "Hamburg", website: "https://uni-hamburg.de" },
  { slug: "university-of-hildesheim", name: "University of Hildesheim", city: "Hildesheim", website: "https://www.uni-hildesheim.de/" },
  { slug: "university-of-hohenheim", name: "University of Hohenheim", city: "Stuttgart", website: "https://www.uni-hohenheim.de/" },
  { slug: "university-of-kaiserslautern-landau", name: "University of Kaiserslautern-Landau", city: null, website: "https://rptu.de/" },
  { slug: "university-of-kassel", name: "University of Kassel", city: "Kassel", website: "https://www.uni-kassel.de" },
  { slug: "university-of-koblenz", name: "University of Koblenz", city: "Koblenz", website: "https://www.uni-koblenz.de/de" },
  { slug: "university-of-konstanz", name: "University of Konstanz", city: "Constance", website: "https://www.uni-konstanz.de/" },
  { slug: "university-of-labour", name: "University of Labour", city: "Frankfurt", website: "https://www.university-of-labour.de/" },
  { slug: "university-of-lubeck", name: "University of Lübeck", city: "Schleswig-Holstein", website: "https://www.uni-luebeck.de/" },
  { slug: "university-of-magdeburg", name: "University of Magdeburg", city: "Saxony-Anhalt", website: "http://www.ovgu.de/" },
  { slug: "university-of-mannheim", name: "University of Mannheim", city: "Mannheim", website: "https://www.uni-mannheim.de/" },
  { slug: "university-of-marburg", name: "University of Marburg", city: "Marburg", website: "https://www.uni-marburg.de/" },
  { slug: "university-of-music-and-theatre-leipzig", name: "University of Music and Theatre Leipzig", city: "Leipzig", website: "https://www.hmt-leipzig.de/" },
  { slug: "university-of-music-and-theatre-munich", name: "University of Music and Theatre Munich", city: "Munich", website: "https://hmtm.de/" },
  { slug: "university-of-munster", name: "University of Münster", city: "Münster", website: "https://www.uni-muenster.de/" },
  { slug: "university-of-oldenburg", name: "University of Oldenburg", city: "Oldenburg", website: "https://uol.de/" },
  { slug: "university-of-paderborn", name: "University of Paderborn", city: "North Rhine-Westphalia", website: "https://www.uni-paderborn.de" },
  { slug: "university-of-passau", name: "University of Passau", city: "Passau", website: "https://www.uni-passau.de/" },
  { slug: "university-of-potsdam", name: "University of Potsdam", city: "Potsdam", website: "https://www.uni-potsdam.de/" },
  { slug: "university-of-regensburg", name: "University of Regensburg", city: "Regensburg", website: "https://www.uni-regensburg.de/" },
  { slug: "university-of-rostock", name: "University of Rostock", city: "Rostock", website: "https://www.uni-rostock.de/" },
  { slug: "university-of-siegen", name: "University of Siegen", city: "Siegen", website: "https://www.uni-siegen.de/" },
  { slug: "university-of-stuttgart", name: "University of Stuttgart", city: "Stuttgart", website: "https://www.uni-stuttgart.de" },
  { slug: "university-of-technology-nuremberg", name: "University of Technology Nuremberg", city: "Nuremberg", website: "https://www.utn.de/" },
  { slug: "university-of-television-and-film-munich", name: "University of Television and Film Munich", city: "Maxvorstadt", website: "http://www.hff-muc.de" },
  { slug: "university-of-tubingen", name: "University of Tübingen", city: "Tübingen", website: "https://uni-tuebingen.de/" },
  { slug: "university-of-vechta", name: "University of Vechta", city: "Vechta", website: "http://www.uni-vechta.de/" },
  { slug: "university-of-veterinary-medicine-hannover", name: "University of Veterinary Medicine Hannover", city: null, website: "https://www.tiho-hannover.de/" },
  { slug: "university-of-wurzburg", name: "University of Würzburg", city: "Würzburg", website: "http://www.uni-wuerzburg.de/" },
  { slug: "university-of-applied-science-for-international-management", name: "University of applied science for international management", city: "Heidelberg", website: "http://www.himh.de" },
  { slug: "university-of-applied-science-in-finance-nordrhein-westfalen", name: "University of applied science in Finance Nordrhein-Westfalen", city: "Nordkirchen", website: "http://www.fhf-nordkirchen.de/" },
  { slug: "university-of-the-arts-bremen", name: "University of the Arts Bremen", city: "Bremen", website: "https://www.hfk-bremen.de/" },
  { slug: "university-of-the-bundeswehr-munich", name: "University of the Bundeswehr Munich", city: "Neubiberg", website: "https://www.unibw.de/" },
  { slug: "universitatsmedizin-gottingen", name: "Universitätsmedizin Göttingen", city: "Göttingen", website: "https://www.umg.eu/" },
  { slug: "victoria-international-university-of-applied-sciences", name: "VICTORIA | International University of Applied Sciences", city: "Berlin", website: "http://www.hwtk.de/" },
  { slug: "vwa-hochschule", name: "VWA Hochschule", city: "Stuttgart", website: "http://www.vwa-hochschule.de/" },
  { slug: "vwa-und-berufsakademie-gottingen", name: "VWA und Berufsakademie Göttingen", city: "Göttingen", website: "http://www.vwa-goettingen.de/" },
  { slug: "verwaltungsfachhochschule-rotenburg-an-der-fulda", name: "Verwaltungsfachhochschule Rotenburg an der Fulda", city: "Rotenburg an der Fulda", website: "http://www.studienzentrum-rotenburg.de/" },
  { slug: "vinzenz-pallotti-university", name: "Vinzenz Pallotti University", city: "Vallendar", website: "http://www.pthv.de" },
  { slug: "whu-otto-beisheim-school-of-management", name: "WHU – Otto Beisheim School of Management", city: "Vallendar", website: "http://www.whu.edu" },
  { slug: "weihenstephan-triesdorf-university-of-applied-science", name: "Weihenstephan-Triesdorf University of Applied Science", city: "Freising", website: "http://www.hswt.de/" },
  { slug: "weingarten-university-of-education", name: "Weingarten University of Education", city: "Ravensburg District", website: "https://www.ph-weingarten.de/" },
  { slug: "weissensee-academy-of-art-berlin", name: "Weißensee Academy of Art Berlin", city: "Pankow", website: "https://www.kh-berlin.de/" },
  { slug: "welfenakademie-braunschweig", name: "Welfenakademie Braunschweig", city: "Hanover", website: "http://www.welfenakademie.de" },
  { slug: "westphalian-university-of-applied-sciences-gelsenkirchen-bocholt-recklinghausen", name: "Westphalian University of Applied Sciences Gelsenkirchen Bocholt Recklinghausen", city: "North Rhine-Westphalia", website: "http://www.w-hs.de/" },
  { slug: "westsachsische-hochschule-zwickau-university-of-applied-sciences", name: "Westsächsische Hochschule Zwickau - University of Applied Sciences", city: "Zwickau", website: "https://www.fh-zwickau.de/" },
  { slug: "whitecliffe-university-of-applied-sciences", name: "Whitecliffe University of Applied Sciences", city: null, website: "https://www.berlin-international.de" },
  { slug: "wildau-institute-of-technology", name: "Wildau Institute of Technology", city: "Wildau", website: "http://www.wit-wildau.de/" },
  { slug: "wilhelm-buchner-hochschule", name: "Wilhelm Büchner Hochschule", city: "Darmstadt", website: "http://www.wb-fernstudium.de/" },
  { slug: "wilhelmsstift", name: "Wilhelmsstift", city: "Tübingen", website: "https://www.wilhelmsstift.de" },
  { slug: "witten-herdecke-university", name: "Witten/Herdecke University", city: "Witten", website: "https://www.uni-wh.de/" },
  { slug: "xu-exponential-university", name: "XU Exponential University", city: "Potsdam", website: "https://xu-university.com" },
  { slug: "ymca-university-of-applied-sciences", name: "YMCA University of Applied Sciences", city: "Kassel", website: "http://www.cvjm-hochschule.de/" },
  { slug: "zeppelin-university", name: "Zeppelin University", city: "Friedrichshafen", website: "https://www.zu.de/" },
  { slug: "zittau-gorlitz-university-of-applied-sciences", name: "Zittau/Görlitz University of Applied Sciences", city: "Görlitz", website: "https://www.hszg.de/" },
  { slug: "college-21", name: "college 21", city: "Buxtehude", website: "http://www.hs21.de/" },
  { slug: "htw-saar-saarland-university-of-applied-sciences", name: "htw saar | Saarland University of Applied Sciences", city: null, website: "https://www.htwsaar.de/" },
];

export const UNI_SLUGS: readonly string[] = GERMAN_UNIS.map((u) => u.slug);
const BY_SLUG = new Map(GERMAN_UNIS.map((u) => [u.slug, u]));
export function findUniBySlug(slug: string): GermanUni | null {
  return BY_SLUG.get(slug) ?? null;
}
